[package]
name = "web_stack"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.90"
regex = "0.1"
opener = "0.6.1"
rand = "0.8"
reqwest = { version = "0.11.0", features = ["blocking"] }
rodio = "0.17.3"